### ISSUE TITLE
foo\*txt should match foo*txt (and also not match foo.txt)

### ISSUE THREAD

**Issue by GuyMograbi** [nielsbasjes/codeowners#77]
If I have a file named `foo*txt`  (mkdir `foo\*txt`) and file foo.txt

by adding the rule `foo\*txt` to gitignore, I should be able to ignore one but not the other. 

Current implementation will not detect a hit on foo*txt file

**Comment by nielsbasjes** [comment]
Thanks for bringing this up.
The official documentation doesn't mention this at all. I'm going to try this out with the real git first and then improve my code in this regard.

**Comment by nielsbasjes** [comment]
Fixed.
I've also added tests for the same thing with a '?'
